version: "1"
services:
  cloudflare-c:
    image: cloudflare/cloudflared:1449-569a7c3c9ed0
    restart: unless-stopped
    command: tunnel run --token eyJhIjoiNDUwZjBjZGQ2YzI0OWU3NWM3YjFiMjk5OWI3NWQwZjciLCJ0IjoiMjZiYThhNTAtNWY1Yi00Mzc4LTk3ODUtYzMyNDZhNTg4NDU4IiwicyI6Ik56TTJZakV5TlRrdFlUbG1OUzAwTW1Wa0xUZ3lOemt0TWpCak0ySTNORGN6TTJFMSJ9
    volumes:
      - ./tunnel:/etc/cloudflared
  mongo-c:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./datos/mongodb:/data/db
  spring-c:
    build: .
    environment:
      NUKA_PUERTO: 9898
      NUKA_HOST: puertocho.com
      NUKA_DEBUG_MODE: true
      NUKA_OPENAI_KEY: sk-proj-wEUeltuyVov8vT1zRLp4T3BlbkFJs688hAwTQBUosqGkCzNG
      NUKA_MONGO_BD_NAME: master
      NUKA_MONGO_USERNAME: root
      NUKA_MONGO_PASSWORD: example
      NUKA_MONGO_PUERTO: 27017
      NUKA_MONGO_EQUIPO: mongo-c
      NUKA_MICROSOFT_COG_KEY: e32664f8376c485e92de564fa2dfbc22
      NUKA_MICROSOFT_COG_REGION: westeurope
      NUKA_KEY_KWT: Antonio13
    ports:
      - "9898:9898"
    links:
      - mongo-c
    volumes:
      - ./datos/datos_server:/var/datos
